site_name: "Grupo A - Urban Air Mobility - IT 214"

theme:
  name: material
  features:
    - navigation.tabs  # Habilita navegação superior
  palette:
    primary: "#7CFC00"  # Cor da barra de menus (verde-limão)
    accent: "#FFFFFF"   # Cor dos botões e links (branco)

nav:
  - Home: index.md
  - Atividade 1: atv1.md
